version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: aicapital-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: aicapital
    volumes:
      - mongodb_data:/data/db
    networks:
      - aicapital-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    container_name: aicapital-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb+srv://avi648elastic_db_user:5O5Wbs9ylneOOEVq@ai0.4erhngv.mongodb.net/aicapital?retryWrites=true&w=majority&appName=AI0
      JWT_SECRET: AIcap2025superSecretKey984
      GOOGLE_SHEETS_API_KEY: AIzaSyABPq2Hvbbdl_OZSudGynqNBSPy2B6i8lU
      GOOGLE_SHEETS_SHEET_ID: 2PACX-1vQqGMWLbx3fF3y_g4Cf7AKitM0PP4LhxJg0h9_rnFnUNrJpDAdKicxkk-f53qoossKNBZJkNNACDxWm
    depends_on:
      - mongodb
    networks:
      - aicapital-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    container_name: aicapital-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - aicapital-network

volumes:
  mongodb_data:

networks:
  aicapital-network:
    driver: bridge
