version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: aicapital-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: aicapital
    volumes:
      - mongodb_data:/data/db
    networks:
      - aicapital-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: aicapital-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/aicapital?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GOOGLE_SHEETS_API_KEY: your-google-sheets-api-key
      GOOGLE_SHEETS_SHEET_ID: your-google-sheet-id
    depends_on:
      - mongodb
    networks:
      - aicapital-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: aicapital-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - aicapital-network

volumes:
  mongodb_data:

networks:
  aicapital-network:
    driver: bridge
