# Render.com deployment configuration for AiCapital
services:
  - type: web
    name: aicapital-backend
    env: node
    plan: starter
    buildCommand: |
      cd backend && npm ci --only=production && npm run build
      cd ../frontend && npm ci --only=production && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: aicapital-mongodb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: aicapital-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINANCIAL_MODELING_PREP_API_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  - name: aicapital-mongodb
    plan: starter
    databaseName: aicapital

  - name: aicapital-redis
    plan: starter
    type: redis